version: '3.2'

services:
  web-api:
    container_name: 'auto-ticket-system-api'
    build: .
    ports:
      - '3000:3000'
    environment:
      - 'AUTO_TICKET_SYSTEM_DB_HOST=auto-ticket-system-db'
    links:
      - 'database'
  database:
    container_name: 'auto-ticket-system-db'
    image: 'mongo'
